#!/usr/bin/env node
// C2 codegen: src/domain/pipeline/registry.ts DESCRIPTORS are the SINGLE SOURCE
// OF TRUTH for node topology. This script regenerates every shadow home:
//   (a) the audit_graph section of state/graph-state.json,
//   (b) contracts/node-contracts/<ID>.md structured front-matter (prose between
//       <!-- prose:start -->/<!-- prose:end --> markers is preserved verbatim;
//       a missing marker on an existing file fails LOUD instead of clobbering),
//   (c) the contracts/node-contracts/README.md index table.
// Output is deterministic byte-for-byte (no clock reads, fixed key order).
// `--check` writes nothing: it compares computed bytes against disk and exits 1
// listing drifts — scripts/validate-state.mjs shells out to this mode in CI.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { stringify as yamlStringify } from "yaml";
import { DESCRIPTORS } from "../src/domain/pipeline/registry";
import {
  AG_NODE_IDS,
  PAYLOAD_KINDS,
  SHARED_STATE_SLICES,
  type NodeDescriptor,
} from "../src/domain/pipeline/types";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GRAPH_PATH = path.join(ROOT, "state", "graph-state.json");
const CONTRACTS_DIR = path.join(ROOT, "contracts", "node-contracts");
const PROSE_START = "<!-- prose:start -->";
const PROSE_END = "<!-- prose:end -->";

const GENERATED_NOTICE =
  "<!-- The yaml block below is GENERATED by scripts/gen-node-topology.ts from\n" +
  "     src/domain/pipeline/registry.ts DESCRIPTORS (single source of truth).\n" +
  "     Regenerate via `npm run gen:nodes`; human edits belong between the\n" +
  "     prose:start/prose:end markers only. -->";

interface GraphNode {
  id: string;
  impl: string;
  name: string;
  role: string;
  node_class: string;
  producer: string;
  reads: string[];
  writes: string[];
  emits: string;
  depends_on: string[];
  executed_in_batch: boolean;
}

interface GraphEdge {
  from: string;
  type: "DATA" | "DEPENDENCY";
  to: string;
  payload: string;
}

function validateDescriptors(): string[] {
  const errors: string[] = [];
  const seen = new Set<string>();
  DESCRIPTORS.forEach((d, index) => {
    if (seen.has(d.id)) errors.push(`duplicate descriptor id ${d.id}`);
    seen.add(d.id);
    if (AG_NODE_IDS[index] !== d.id) {
      errors.push(`descriptor order diverges from AG_NODE_IDS at index ${index}: ${d.id}`);
    }
    for (const dep of d.depends_on) {
      if (!AG_NODE_IDS.includes(dep)) errors.push(`${d.id}: unknown depends_on entry ${dep}`);
      else if (AG_NODE_IDS.indexOf(dep) >= index) {
        errors.push(`${d.id}: depends_on ${dep} is not a predecessor`);
      }
    }
    for (const slice of [...d.reads, ...d.writes]) {
      if (!SHARED_STATE_SLICES.includes(slice)) {
        errors.push(`${d.id}: unknown slice ${slice}`);
      }
    }
    if (!PAYLOAD_KINDS.includes(d.emits)) errors.push(`${d.id}: unknown payload kind ${d.emits}`);
    if (d.executed_in_batch !== (d.id !== "AG-PERSIST")) {
      errors.push(`${d.id}: executed_in_batch disagrees with batch membership`);
    }
    const implFile = d.impl.split(" ")[0];
    if (!fs.existsSync(path.join(ROOT, implFile))) {
      errors.push(`${d.id}: impl path does not exist on disk: ${implFile}`);
    }
  });
  return errors;
}

function deriveEdges(): GraphEdge[] {
  const byId = new Map(DESCRIPTORS.map((d) => [d.id, d]));
  const edges: GraphEdge[] = [];
  for (const node of DESCRIPTORS) {
    for (const depId of node.depends_on) {
      const dep = byId.get(depId);
      if (!dep) continue;
      const handoff = dep.writes.filter((w) => node.reads.includes(w));
      edges.push(
        handoff.length
          ? { from: dep.id, type: "DATA", to: node.id, payload: `${dep.id} hands off ${handoff.join(", ")}` }
          : { from: dep.id, type: "DEPENDENCY", to: node.id, payload: `${node.id} orders after ${dep.id} (no direct slice handoff)` },
      );
    }
  }
  return edges;
}

function buildAuditGraph(): { purpose: string; nodes: GraphNode[]; edges: GraphEdge[] } {
  return {
    purpose: "Bounded-context graph the product executes to run an actual audit (§19); GENERATED from registry.ts DESCRIPTORS by scripts/gen-node-topology.ts.",
    nodes: DESCRIPTORS.map((d) => ({
      id: d.id,
      impl: d.impl,
      name: d.name,
      role: d.summary,
      node_class: d.node_class,
      producer: d.producer,
      reads: [...d.reads],
      writes: [...d.writes],
      emits: d.emits,
      depends_on: [...d.depends_on],
      executed_in_batch: d.executed_in_batch,
    })),
    edges: deriveEdges(),
  };
}

function renderGraphState(): string {
  const doc = JSON.parse(fs.readFileSync(GRAPH_PATH, "utf8"));
  if (!doc.graphs?.audit_graph) {
    throw new Error("state/graph-state.json has no graphs.audit_graph section");
  }
  doc.graphs.audit_graph = buildAuditGraph();
  // updated_at and development_graph are intentionally untouched (no clock reads).
  return JSON.stringify(doc, null, 2) + "\n";
}

function extractProse(existing: string, filePath: string): { prose: string; error?: string } {
  const start = existing.indexOf(PROSE_START);
  const end = existing.indexOf(PROSE_END);
  if (start === -1 || end === -1 || end < start) {
    return {
      prose: "",
      error:
        `${path.relative(ROOT, filePath)}: prose markers (${PROSE_START}…${PROSE_END}) missing or inverted; ` +
        "refusing to regenerate — wrap human-edited content in markers first",
    };
  }
  const inner = existing.slice(start + PROSE_START.length, end);
  return { prose: inner.startsWith("\n") ? inner.slice(1) : inner };
}

function renderContract(descriptor: NodeDescriptor, prose: string): string {
  const frontMatter = {
    node_id: descriptor.id,
    title: descriptor.name,
    role: descriptor.summary,
    impl: descriptor.impl,
    producer: descriptor.producer,
    determinism_class: descriptor.node_class,
    emits: descriptor.emits,
    executed_in_batch: descriptor.executed_in_batch,
    state: { reads: [...descriptor.reads], writes: [...descriptor.writes] },
    depends_on: [...descriptor.depends_on],
  };
  const body = yamlStringify(frontMatter, { lineWidth: 100 });
  return (
    `# Node Contract: ${descriptor.name}\n\n${GENERATED_NOTICE}\n\n` +
    "```yaml\n" +
    body +
    "```\n\n" +
    `${PROSE_START}\n${prose}${PROSE_END}\n`
  );
}

function renderContracts(): Map<string, string> {
  const rendered = new Map<string, string>();
  for (const d of DESCRIPTORS) {
    const filePath = path.join(CONTRACTS_DIR, `${d.id}.md`);
    let existing: string | null = null;
    try {
      existing = fs.readFileSync(filePath, "utf8");
    } catch {
      existing = null;
    }
    let prose = "";
    if (existing !== null) {
      const extracted = extractProse(existing, filePath);
      if (extracted.error) throw new Error(extracted.error);
      prose = extracted.prose;
    } else {
      prose =
        "### Purpose\n\nTODO: describe this node's contract.\n";
    }
    rendered.set(`${d.id}.md`, renderContract(d, prose));
  }
  return rendered;
}

function renderReadme(): string {
  const rows = DESCRIPTORS.map((d) =>
    [
      d.id,
      d.name,
      d.node_class,
      d.reads.length ? d.reads.join(", ") : "—",
      d.writes.join(", "),
      d.emits,
      `\`${d.impl.split(" ")[0]}\``,
      d.producer,
    ].join(" | "),
  );
  const table =
    ["| Node | Title | Class | Reads | Writes | Emits | Impl | Producer |", "|---|---|---|---|---|---|---|---|"]
      .concat(rows.map((r) => `| ${r} |`))
      .join("\n");
  return `# Audit Graph Node Contracts (N1)

<!-- The table below is GENERATED by scripts/gen-node-topology.ts from
     src/domain/pipeline/registry.ts DESCRIPTORS. Regenerate via
     \`npm run gen:nodes\`; do not hand-edit between table:start/table:end. -->

One contract per audit_graph node (see state/graph-state.json). Shared slice
names and the AuditArtifact envelope are defined in [SHARED-STATE.md](SHARED-STATE.md).
Template shape: [TEMPLATE.md](TEMPLATE.md). Determinism classes: deterministic /
ai-bounded / human. Doctrine: deterministic-first; AI proposes bounded candidates,
adjudication disposes; compliance ≠ safety.

<!-- table:start -->
${table}
<!-- table:end -->
`;
}

function firstDiff(computed: string, onDisk: string): string {
  const a = computed.split("\n");
  const b = onDisk.split("\n");
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) return `line ${i + 1}: expected ${JSON.stringify(a[i] ?? "<eof>")}, found ${JSON.stringify(b[i] ?? "<eof>")}`;
  }
  return "identical";
}

function main(): number {
  const descriptorErrors = validateDescriptors();
  if (descriptorErrors.length) {
    console.error("DESCRIPTOR VALIDATION FAILED:");
    for (const e of descriptorErrors) console.error(`  - ${e}`);
    return 1;
  }

  const checkOnly = process.argv.includes("--check");
  try {
    // Compute every home first; any missing-marker or validation problem fails
    // LOUD here, before a single byte is written.
    const targets = new Map<string, string>();
    targets.set("state/graph-state.json", renderGraphState());
    for (const [file, bytes] of renderContracts()) {
      targets.set(`contracts/node-contracts/${file}`, bytes);
    }
    targets.set("contracts/node-contracts/README.md", renderReadme());

    const drifts: string[] = [];
    for (const [label, computed] of targets) {
      const abs = path.join(ROOT, label);
      if (checkOnly) {
        const onDisk = fs.readFileSync(abs, "utf8");
        if (onDisk !== computed) drifts.push(`${label}: DRIFT (${firstDiff(computed, onDisk)})`);
        continue;
      }
      fs.writeFileSync(abs, computed);
    }

    if (checkOnly) {
      if (drifts.length) {
        console.error("NODE TOPOLOGY DRIFT DETECTED (run `npm run gen:nodes`):");
        for (const d of drifts) console.error(`  - ${d}`);
        return 1;
      }
      console.log(`node topology --check: OK (${targets.size} generated homes byte-stable vs registry.ts)`);
      return 0;
    }
    console.log(`node topology written: ${targets.size} homes regenerated from registry.ts DESCRIPTORS`);
    return 0;
  } catch (e) {
    console.error(`GEN-NODE-TOPOLOGY FAILED: ${e instanceof Error ? e.message : String(e)}`);
    return 1;
  }
}

process.exit(main());
